version: '3.8'

services:
  react-app:
    build:
      context: ./react-portfolio
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
