version: "3.8"
services: 
    mysql: 
        image: mysql:5.7.36
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "7001:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./db/mysql:/var/lib/mysql
        networks:
            - camcyber

    api: 
        container_name: pos-api-v1
        restart: unless-stopped
        tty: true
        build: 
            context: ./api/.
            dockerfile: Dockerfile
        volumes: 
            - ./api/app:/var/www/app
            - ./api/resources:/var/www/resources
            - ./api/routes:/var/www/routes
            - ./api/storage:/var/www/storage
            - ./api/database:/var/www/database
        command: php artisan serve --host=0.0.0.0 --port=8000
        ports:
            - "8002:8000"
        environment: 
            APP_KEY: base64:mNe36k6bz1cidhh1dLtMtjRsiMnMOyjztjti7a6rAf4=
            JWT_SECRET: MTO7OmBzXhbPI2bErLjV9XEFbpCn3MHCPxKdcBxiFHjuWJirIayTB9npa4cGNAFX
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: minimart
            DB_USERNAME: root
            DB_PASSWORD: secret
            FILE_URL: http://file:8000
            JS_BASE_URL: pos-report-v1:5488
            JS_USERNAME: admin
            JS_PASSWORD: secret
            TELEGRAM_BOT_TOKEN: 7214170701:AAEYEq5Paq6IMAO2lfn4fMR-ivbYvt0XHvk
            TELEGRAM_CHAT_ID: -1002178540175
            MAIL_MAILER: ''
            MAIL_HOST: ''
            MAIL_PORT: ''
            MAIL_USERNAME: ''
            MAIL_PASSWORD: ''
            MAIL_ENCRYPTION: ''
            MAIL_FROM_ADDRESS: ''
            MAIL_FROM_NAME: ''
        networks: 
            - camcyber

    file: 
        container_name: pos-file-v1  
        build: 
            context: ./file/.
            dockerfile: Dockerfile
        volumes: 
            - ./file/public:/var/www/public
        command: php artisan serve --host=0.0.0.0
        ports:
            - "8003:8000"
        networks: 
            - camcyber

    report: 
        image: jsreport/jsreport
        container_name: pos-report-v1
        ports:
            - "8004:5488"
        networks:
            - camcyber

    web: 
        container_name: pos-web-v1
        build:
            context: ./web/.
            dockerfile: Dockerfile
        ports:
            - "8005:80"
        networks: 
            - camcyber

networks: 
    camcyber:
